name: Conso_Net
description: "Sustainable solution for construction"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.11
  cupertino_icons: ^1.0.8
  characters: ^1.3.0
  collection: ^1.18.0
  material_color_utilities: 0.11.1
  meta: 1.15.0
  path: 1.9.0

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/



  fonts:
    - family: Inter
      fonts:
        - asset: Inter/Inter-VariableFont_opsz,wght.ttf


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0  # Updated to a compatible version
  async: ^2.11.0
  boolean_selector: ^2.1.1
  clock: ^1.1.1
  fake_async: ^1.3.1
  leak_tracker: ^10.0.5
  leak_tracker_flutter_testing: ^3.0.5
  matcher: ^0.12.16+1
  stack_trace: ^1.11.1